### PR TITLE
Add addon manager

### PR DESCRIPTION
**Pull request by carsakiller**
Adds an addon manager that adds a command (`lua.addon_manager.open`), webview, and setting (`Lua.addonManager.authentication.noAsk`).

The webview runs the [`vscode-lua-webvue`](https://github.com/carsakiller/vscode-lua-webvue) web app and allows the user to install, enable, disable, and uninstall addons from the [`LLS-Addons` repo](https://github.com/carsakiller/LLS-Addons).

It is highly recommended that users sign in, as unfortunately, the GitHub API rate limit for unauthenticated traffic is very low and users are likely to get rate limited pretty quickly.

### CODE REVIEW

**Comment by carsakiller** [comment]
Looks like this PR needs approval in order for the build action to run, so I can test if the `vsix` has built correctly.

**Comment by carsakiller** [comment]
I have given things a test, and it is looking good from my end! I was also able to shrink the vsix package down a bit by not including all the node modules.

**Comment by carsakiller** [comment]
It is annoying to have a popup appear, but I could not fit all the info in the small VS Code toast message. It won't appear anymore if the user signs in or selects "Stop Asking". Do you know of a better way to prompt the user?

**Comment by sumneko** [comment]
I'd better prompt after using `lua.addon_manager.open`

**Comment by carsakiller** [comment]
Oh! It is appearing on startup of the extension for you 😳. It is only supposed to prompt you after running `lua.addon_manager.open`. I think I know the cause.

**Comment by carsakiller** [comment]
I have a fix that should now only ask the user after running `lua.addon_manager.open`. Anything else you have noticed?

**Comment by sumneko** [comment]
I think it should also set `checkThirdParty` to `false`

**Comment by carsakiller** [comment]
`checkThirdParty` is now `false` after opening the addon manager

**Comment by carsakiller** [comment]
@sumneko I have thought a bit more about how we can leverage submodules with the [LLS-Addons repo](https://github.com/carsakiller/LLS-Addons). Ideally, each addon could be its own submodule, making it easier for contributions to be made. Then authors could have their addon live elsewhere and not have to copy their entire project over.

In order to support this, there are changes required that would break backwards compatibility. I think we should delay releasing this for now while I further research how best to use submodules. If you need to make a release of `vscode-lua`, please revert the merge commit.

**Comment by sumneko** [comment]
OK, I reverted it.

**Comment by sumneko** [comment]
Besides, you should modify config by command:

```ts
this.client.sendRequest(ExecuteCommandRequest.method, {
    command: 'lua.setConfig',
    arguments: [
        {
            key    : 'workspace.checkThirdParty',
            action : 'set',
            value  : false,
            uri    : uri,
        }
    ]
})
```

It can handle `.luarc.json`.
The arg `uri` is used for multi-workspace, if user opened multi-workspace, user should select one of them.

**Comment by carsakiller** [comment]
Is there a similar command that allows me to read the config, whether it be `settings.json` or `.luarc`?

**Comment by carsakiller** [comment]
Because I need somewhere more convenient than my own account to store all the addons (which are now all meant to be their own repository), I created the [LuaCATS](https://github.com/LuaCATS) organization.

I'm not sure if you would prefer the "official" addons be a part of the organization you are going to create or this [LuaCATS](https://github.com/LuaCATS) one. Let me know if you like the idea and I can add you or if you would prefer something else.

I am also trying to find a way to pick the commits from the language server that modify the "official" definitions so that I can credit those that helped make them and keep the git history.

**Comment by carsakiller** [comment]
This doesn't seem to apply the setting:
```ts
import { defaultClient } from "../../languageserver";
import { ExecuteCommandRequest } from "vscode-languageclient";

defaultClient.client.sendRequest(ExecuteCommandRequest.method, {
    command: "lua.setConfig",
    arguments: [
        {
            key: "workspace.checkThirdParty",
            action: "set",
            value: false,
            uri: folder.uri,
        },
    ],
});
```
`folder` is of `vscode.workspaceFolder` type, therefor `folder.uri` is a `vscode.Uri`.

**Comment by carsakiller** [comment]
I was able to copy over a bunch of the meta projects that are currently in the language server repo to [LuaCATS](https://github.com/LuaCATS) with their history :tada:.

I also rewrote the addon manager to use git and the submodules from [LLS-Addons](https://github.com/carsakiller/LLS-Addons) instead of the GitHub API. This means that users no longer have to sign in (yay), but you need Git installed, and GitLab repos are no longer supported 😢.

I am going to wait until the organization for all of this is created before trying to merge the addon manager in, as when the repos are all moved to the new organization it will break everything.

**Comment by sumneko** [comment]
I have exported API `setConfig` and `getConfig`

**Comment by carsakiller** [comment]
I can't seem to get `getConfig` to work. I [attempt to get `Lua.workspace.library`](https://github.com/carsakiller/vscode-lua/blob/bae8747e61327c379e67f237221ce7c9f33d57b5/client/src/addon_manager/services/settings.service.ts#L25), but it seems that it is always returning `null`

**Comment by sumneko** [comment]
I have updated them

**Pull request merged**
